### ISSUE TITLE
Navigation bar does not properly collapse on some pages

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisweb#1687] opened 2023-08-23 15:32 UTC
### Current behaviour

Originally reported by an upcoming freshmen (introkiddo)

https://github.com/GEWIS/gewisweb/assets/17340320/5d28305a-de9c-402d-b34b-dc8707840f3f

### Steps to reproduce

See video

### Website version

6b4078b00

**Comment by tomudding** [comment] 2023-08-23 15:46
Known issue, preferably I would like Bootstrap 5 instead of trying to fix it.

**Comment by tomudding** [comment] 2023-08-26 11:20
We have other weird behaviour on the `/admin/*` pages too, where closing/opening one of the navbars also closes/opens the other one.

**Comment by tomudding** [comment] 2023-08-26 18:28
This is caused by the `default` that is used to open the normally collapsed sub-menu:

https://github.com/GEWIS/gewisweb/blob/2ba9e5aee4df4667ee8bb5cee27ab6253df56e58/module/Application/view/partial/main-nav.phtml#L186-L187
https://github.com/GEWIS/gewisweb/blob/2ba9e5aee4df4667ee8bb5cee27ab6253df56e58/module/Application/view/partial/main-nav.phtml#L323
https://github.com/GEWIS/gewisweb/blob/2ba9e5aee4df4667ee8bb5cee27ab6253df56e58/module/Application/view/partial/main-nav.phtml#L371

**Comment by tomudding** [comment] 2023-08-26 19:46
I do not like finding a simple and trivial solution after spending more than an hour trying to get a _now_ complex solution to work.

**Closed** 2023-08-26 20:17 UTC
Labels: Type: Bug, Priority: Low, For: Frontend, Status: Confirmed

**Comment by tomudding** [comment] 2023-08-26 20:27
> We have other weird behaviour on the `/admin/*` pages too, where closing/opening one of the navbars also closes/opens the other one. Perhaps this can be fixed at the same time before Bootstrap 5 (as that is 'not soon'™).

This has been fixed in 1b2f73cf84618210805e98c0701b10aaa1d1853f.
