### ISSUE TITLE
Organ pages broken

### ISSUE THREAD

**Issue by Gijsdeman** [GEWIS/gewisweb#1211] opened 2021-09-02 09:14 UTC
Yesterday I noticed that none of the organ pages reachable from [https://gewis.nl/organ](https://gewis.nl/organ) are working. I suppose this is something that went wrong when the website moved to the new server.

**Comment by Koen1999** [comment] 2021-09-02 10:53
This is probably a duplicate of #1186

**Comment by tomudding** [comment] 2021-09-02 11:03
> This is probably a duplicate of #1186

Yes

**Closed** 2021-09-02 11:08 UTC
