### ISSUE TITLE
Manually add participant after activity deadline

### ISSUE THREAD

**Issue by armandduijn** [GEWIS/gewisweb#669] opened 2016-11-18 11:03 UTC
**Problem**
For an activity, we needed 24 participants to subscribe. We set an arbitrary deadline to give us some breathing room if the required number of participants wasn't reached. Unfortunately, when the deadline passed we didn't have enough participants so in the days following the deadline we tried convincing people to join anyways. However, because the activity deadline had passed, the new participants couldn't subscribe to the activity. Even manually adding the participant by an organ member wasn't possible.

**Why**
The reason why this feature is convenient is because I expect the GEWIS activity page to be a single place of truth. I don't like keeping track of the participants in different locations (e.g. Excel, GEWIS).

**Comment by jszanto** [comment] 2016-11-18 14:38
Duplicate of #655

**Closed by jszanto** 2016-11-18 14:38 UTC
Labels: duplicate, feature
