### ISSUE TITLE
Number of vacancies on company overview page does not match actual number of vacancies

### ISSUE THREAD

**Issue by BorBorBor** [GEWIS/gewisweb#748] opened 2017-04-20 18:42 UTC
E.g. currently TNO has 3 (says 38), Topicus has 3 (says 6).

**Comment by jszanto** [comment] 2017-04-20 20:19
Duplicate of #657

**Comment by jszanto** [comment] 2017-04-20 20:20
However this is a better description of the issue actually

**Comment by BorBorBor** [comment] 2017-04-20 20:21
Ha, kind of explains why I wasn't able to find the other issue.

**Comment by jszanto** [comment] 2017-06-15 14:19
Fixed in https://github.com/GEWIS/gewisweb/commit/8da2a2fb2322f5c1d4aa51737e335071d7019097

**Closed by jszanto** 2017-06-15 14:19 UTC
