### ISSUE TITLE
User registration throws unhandled `EntityNotFoundException`

### ISSUE THREAD

**Issue by Koen1999** [GEWIS/gewisweb#1342] opened 2022-01-30 10:10 UTC
```
[2022-01-29T20:26:57.026827+01:00] gewisweb.ERROR: Doctrine\ORM\EntityNotFoundException: Entity of type 'User\Model\User' for IDs lidnr(10352) was not found in /code/vendor/doctrine/orm/lib/Doctrine/ORM/EntityNotFoundException.php:33 Stack trace:
#0 /code/vendor/doctrine/orm/lib/Doctrine/ORM/Proxy/ProxyFactory.php(138): Doctrine\ORM\EntityNotFoundException::fromClassNameAndIdentifier('User\\Model\\User', Array)
#1 /code/data/DoctrineORMModule/Proxy/__CG__UserModelUser.php(244): Doctrine\ORM\Proxy\ProxyFactory->Doctrine\ORM\Proxy\{closure}(Object(DoctrineORMModule\Proxy\__CG__\User\Model\User), 'getMember', Array)
#2 /code/data/DoctrineORMModule/Proxy/__CG__UserModelUser.php(244): Closure->__invoke(Object(DoctrineORMModule\Proxy\__CG__\User\Model\User), 'getMember', Array)
#3 /code/module/Activity/src/Model/UserSignup.php(35): DoctrineORMModule\Proxy\__CG__\User\Model\User->getMember()
#4 /code/module/Activity/src/Service/Signup.php(164): Activity\Model\UserSignup->getFullName()
#5 /code/module/Activity/src/Controller/ActivityController.php(184): Activity\Service\Signup->getSignedUpData(Object(Activity\Model\SignupList))
#6 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Activity\Controller\ActivityController->viewSignupListAction()
#7 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch(Object(Laminas\Mvc\MvcEvent))
#8 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#9 /code/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#10 /code/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch(Object(Laminas\Http\PhpEnvironment\Request), Object(Laminas\Http\PhpEnvironment\Response))
#11 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch(Object(Laminas\Mvc\MvcEvent))
#12 /code/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent), Object(Closure))
#13 /code/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\Mvc\MvcEvent))
#14 /code/public/index.php(20): Laminas\Mvc\Application->run()
#15 {main} [] []
```

**Comment by tomudding** [comment] 2022-01-31 13:14
This is the activity sign-up and not user registration. This person is no longer a GEWIS member, and I haven't run the script to remove them last week.

Duplicate of #1060.

**Closed by tomudding** 2022-01-31 13:14 UTC
Labels: Type: Bug, For: Backend, Module: User
