### ISSUE TITLE
Company slugs do not have to be unique

### ISSUE THREAD

**Issue by jszanto** [GEWIS/gewisweb#488] opened 2016-02-06 12:31 UTC

**Comment by kokx** [comment] 2016-02-06 13:03
What is the exact problem? Is it that they don't need to be unique? Or, is it that they should be unique and the website doesn't force them to be unique?

**Comment by jszanto** [comment] 2016-02-06 13:44
They should be unique and the website doesn't force them to be unique.

**Comment by wsinnema** [comment] 2016-02-07 11:48
Duplicate of #383

**Closed by wsinnema** 2016-02-07 11:48 UTC
Labels: bug, duplicate
