### ISSUE TITLE
How to get the organs a user is in?

### ISSUE THREAD

**Issue by stefanmajoor** [GEWIS/gewisweb#430] opened 2016-01-09 14:26 UTC
How do I get all the organs that a member currently belongs to?

There are two tables:
 - OrganMembers
- MemberOrgan

Why is this?

I created an organ, and in both OrganMembers and MemberOrgan I added myself to the organ, but $member->getOrganInstallations() is still empty. Why is this still empty?

**Comment by jszanto** [comment] 2016-01-09 16:58
Is the dischargeDate NULL in your OrganMember entry? Also afaik there shouldn't be a MemberOrgan table, only an OrganMember table should exist.

**Comment by stefanmajoor** [comment] 2016-01-09 17:16
My DB schema is up to date, and the dischargeDate is indeed NULL

**Comment by jszanto** [comment] 2016-01-09 17:42
Have you tried logging out and in again? (if you're trying to get the organ installations for the currently logged in user)

**Comment by kokx** [comment] 2016-01-09 23:06
`MemberOrgan` was created by @choutha quite a while ago, but was removed because it wasn't part of the database. But the doctrine schema tool doesn't drop tables, because that might destroy data.

Also, you probably need to login again. All that data is fetched at login, and from then on stored in the session.

**Comment by stefanmajoor** [comment] 2016-01-10 20:12
Logging out and in again did indeed help. 

Why is the data refreshed only after I logged in again? And should this be the case, since permission is based upon this? You do not want users to have certain permissions that you can not revoke till they log in again

**Comment by jszanto** [comment] 2016-01-10 20:43
Actually I was mistaken on what getOrganInstallations() should return. It indeed should and does return all organ installations including discharged ones. Perhaps it might be handy to add something like getCurrentOrganInstallations, since there are multiple places in the website.

When a user logs in, the User entity, Member entity, OrganInstallations, etc. are retrieved from the database. Next these objects are stored as session data. This has various benefits, such as not having to fetch all that data again on every page load. Currently there is no persistent session storage, so on the GEWIS server sessions don't last very long. Furthermore organ installations are only synced once every 24 hours from gewisdb so it is not very useful to constantly refresh them and if needed a user session can be destroyed manually. However once we switch to more persistent session storage we will need to find a solution to this issue.

**Comment by stefanmajoor** [comment] 2016-01-10 21:46
I found there were some other complications due to the user being stored. If I loop over the organ installations on the member object the user is associated with, and I call the organ associated with the organMember, then the whole thing blows up (Something, something proxy something). I managed to work around it by fetching the member from the memberservice, thus forcing to get a non catched one.

**Comment by stefanmajoor** [comment] 2016-01-19 07:02
@kokx @jszanto Can either of you comment on the issue I made in my last comment. Is that expected behaviour or a bug?

**Comment by jszanto** [comment] 2016-01-19 08:20
> the whole thing blows up

Doesn't sound like the expected behavior to me.

**Comment by kokx** [comment] 2016-01-19 12:25
@stefanmajoor Without more information than 'Something, something proxy something' really help you.

**Comment by jszanto** [comment] 2016-01-19 21:04
I can't seem to reproduce any major problems except for this one:
```php
$user = $this->sm->get('user_auth_service')->getIdentity();
foreach ($user->getMember()->getOrganInstallations() as $organInstallation) {
    var_dump($organInstallation->getOrgan());
}
```

Results in

```
object(__PHP_Incomplete_Class)[533]
  public '__PHP_Incomplete_Class_Name' => string 'DoctrineORMModule\Proxy\__CG__\Decision\Model\Organ' (length=51)
  public '__isInitialized__' => boolean false
  protected 'id' => int 1300
  protected 'abbr' => null
  protected 'name' => null
  protected 'type' => null
  protected 'foundation' => null
  protected 'foundationDate' => null
  protected 'abrogationDate' => null
  protected 'members' => null
  protected 'subdecisions' => null
```

Is this the intended behavior @kokx?

**Comment by stefanmajoor** [comment] 2016-01-20 07:01
@jszanto Thanks, that was indeed the code that caused the problem.

**Comment by kokx** [comment] 2016-01-20 08:03
Will look into that @jszanto

**Comment by kokx** [comment] 2016-02-03 16:46
This probably can be fixed by calling `class_exists` first on `DoctrineORMModule\Proxy\__CG__\Decision\Model\Organ`.

It might need all proxies to be generated though.

**Closed** 2016-02-04 14:18 UTC
Labels: question
