### ISSUE TITLE
Organ mutations aren't updated

### ISSUE THREAD

**Issue by rinkp** [GEWIS/gewisweb#993] opened 2020-04-07 16:13 UTC
I don't think it is related to #925 but I noticed 'new' organ mutations aren't shown on the committee pages. 
See e.g. [Kas Kontrole Kommissie 2020](https://www.gewis.nl/organ/show/273).
[The mutations from AV172](https://www.gewis.nl/decision/AV/172) are not shown.

**Comment by jszanto** [comment] 2020-04-07 17:26
It’s not a bug, it’s a feature! We have three categories of organs at GEWIS, committees, fraternities and GM committees. For the first two types we have a section on the website, for the last type we don’t. Since KKK20 is a GM committeee it is not shown on the page with committees.

It does actually have a hidden page: https://www.gewis.nl/association/avc/kkk20

**Comment by Koen1999** [comment] 2020-04-10 12:20
I'm wondering whether this is a bug in gewisweb or gewisdb since organ mutations are made in gewisdb

**Comment by tomudding** [comment] 2022-06-14 13:48
This has been fixed by correctly generating reportdb.

**Closed by tomudding** 2022-06-14 13:48 UTC
